'use server'

import { revalidatePath } from 'next/cache'
import { playerFormSchema, uuidSchema } from '@/lib/validations'
import { generateSlug, todayDateString } from '@/lib/utils'
import { getAdminContext } from '@/lib/auth'
import type { z } from 'zod'

type PlayerFormInput = z.infer<typeof playerFormSchema>

export async function createPlayer(data: PlayerFormInput) {
  const { error: authErr, clubId, supabase } = await getAdminContext()
  if (authErr || !supabase || !clubId) return { error: authErr ?? 'errors.unauthorized' }

  const parsed = playerFormSchema.safeParse(data)
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? 'errors.invalidInput' }

  const name = `${parsed.data.first_name} ${parsed.data.last_name}`
  const name_ka = `${parsed.data.first_name_ka} ${parsed.data.last_name_ka}`
  const slug = generateSlug(name)

  // Check for duplicate slug
  const { data: existing } = await supabase
    .from('players')
    .select('id')
    .eq('slug', slug)
    .maybeSingle()

  const finalSlug = existing ? `${slug}-${Date.now().toString(36)}` : slug

  // Insert player (platform_id auto-generated by trigger, status defaults to 'active')
  const { data: newPlayer, error: insertError } = await supabase
    .from('players')
    .insert({
      name,
      name_ka,
      club_id: clubId,
      slug: finalSlug,
      date_of_birth: parsed.data.date_of_birth,
      position: parsed.data.position,
      preferred_foot: parsed.data.preferred_foot ?? null,
      height_cm: parsed.data.height_cm ?? null,
      weight_kg: parsed.data.weight_kg ?? null,
      parent_guardian_contact: parsed.data.parent_guardian_contact ?? null,
      status: 'active',
    })
    .select('id')
    .single()

  if (insertError) return { error: insertError.message }

  // Insert player_club_history row
  if (newPlayer) {
    const { error: historyError } = await supabase
      .from('player_club_history')
      .insert({
        player_id: newPlayer.id,
        club_id: clubId,
        joined_at: todayDateString(),
      })

    if (historyError) console.error('Failed to insert club history:', historyError.message)
  }

  revalidatePath('/admin/players')
  revalidatePath('/players')
  return { success: true, slug: finalSlug }
}

export async function updatePlayer(
  playerId: string,
  data: PlayerFormInput,
) {
  const { error: authErr, clubId, supabase } = await getAdminContext()
  if (authErr || !supabase || !clubId) return { error: authErr ?? 'errors.unauthorized' }

  if (!uuidSchema.safeParse(playerId).success) return { error: 'errors.invalidPlayerId' }

  // Verify player belongs to admin's club
  const { data: existingPlayer, error: checkError } = await supabase
    .from('players')
    .select('id, club_id')
    .eq('id', playerId)
    .single()

  if (checkError || !existingPlayer) return { error: 'errors.playerNotFound' }
  if (existingPlayer.club_id !== clubId) return { error: 'errors.unauthorized' }

  const parsed = playerFormSchema.safeParse(data)
  if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? 'errors.invalidInput' }

  const name = `${parsed.data.first_name} ${parsed.data.last_name}`
  const name_ka = `${parsed.data.first_name_ka} ${parsed.data.last_name_ka}`

  const { error: updateError } = await supabase
    .from('players')
    .update({
      name,
      name_ka,
      date_of_birth: parsed.data.date_of_birth,
      position: parsed.data.position,
      preferred_foot: parsed.data.preferred_foot ?? null,
      height_cm: parsed.data.height_cm ?? null,
      weight_kg: parsed.data.weight_kg ?? null,
      parent_guardian_contact: parsed.data.parent_guardian_contact ?? null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', playerId)

  if (updateError) return { error: updateError.message }

  revalidatePath('/admin/players')
  revalidatePath('/players')
  return { success: true }
}

